### 全件検索
GET http://localhost:8088/users HTTP/1.1
User-Agent: rest-client
content-type: application/json
accept: application/json

### ユーザ登録
POST http://localhost:8088/users HTTP/1.1
User-Agent: rest-client
content-type: application/json

{
  "nickname": "Johnsonnn",
  "mail": "test@test.com"
}

### １件検索
GET http://localhost:8088/users/1 HTTP/1.1
User-Agent: rest-client
content-type: application/json
accept: application/json

### ユーザ更新
PUT http://localhost:8088/users/1 HTTP/1.1
User-Agent: rest-client
content-type: application/json

{
  "nickname": "makaroni",
  "mail": "test2@test.com"
}

### １件削除
DELETE http://localhost:8088/users/1 HTTP/1.1
User-Agent: rest-client
content-type: application/json
accept: application/json